npc:
  sharpening:
    title: 'Дальгриг'
    command: 'sharpening'
    skin: '9cf8d51a-69a4-11ed-bdb3-1cb72cb014ae'
  consumable:
    title: 'Франк'
    command: 'consumable'
    skin: 'bf30a1df-85de-11e8-a6de-1cb72caa35fd'