npc:
  sharpening:
    title: 'Дальгриг'
    command: 'sharpening'
    skin: '9cf8d51a-69a4-11ed-bdb3-1cb72cb014ae'
  consumable:
    title: 'Франк'
    command: 'consumable'
    skin: 'e4115940-69a9-11ed-bcd4-1cb72cb014ae'
  contracts:
    title: 'Франк'
    command: 'contracts'
    skin: 'e4115940-69a9-11ed-bcd4-1cb72cb014ae'
  barter:
    title: 'Франк'
    command: 'contracts'
    skin: 'e4115940-69a9-11ed-bcd4-1cb72cb014ae'